package com.example.ui.theme

object Localization {
    private val dictionary = mapOf(
        "en" to mapOf(
            "app_title" to "NutriScan AI",
            "dashboard" to "Dashboard",
            "scanner" to "AI Scanner",
            "tracker" to "Nutrition Log",
            "favorites" to "Favorites",
            "settings" to "Settings",
            "home" to "Home",
            "history" to "Recent Scans",
            "no_scans" to "No scans made yet. Tap scan to begin!",
            "categories" to "Browse Categories",
            "search_placeholder" to "Search foods or botanical name...",
            "voice_input" to "Tap microphone to search by voice",
            "compare" to "Compare",
            "compare_title" to "Food Comparison",
            "select_to_compare" to "Select foods to compare side-by-side",
            "compare_select_prompt" to "Tap standard history list items to select comparisons below",
            "calories" to "Calories",
            "protein" to "Protein",
            "carbohydrates" to "Carbs",
            "fat" to "Fats",
            "fiber" to "Fiber",
            "scientific_name" to "Scientific Name",
            "category" to "Category",
            "origin" to "Origin",
            "season" to "Peak Season",
            "shelf_life" to "Shelf Life",
            "ayurvedic" to "Ayurvedic Properties",
            "medicinal" to "Medicinal Uses",
            "benefits" to "Health Benefits",
            "precautions" to "Precautions & Safety",
            "allergies" to "Allergies info",
            "recommended_daily" to "Recommended Intakes",
            "add_to_tracker" to "Add to Daily Intake",
            "amount_grams" to "Amount consumed (grams)",
            "save" to "Save",
            "cancel" to "Cancel",
            "daily_summary" to "Daily Goals Tracker",
            "goals" to "Nutritional Goals",
            "edit_goals" to "Adjust Daily Goals",
            "theme" to "App Theme",
            "language" to "App Language",
            "language_switch" to "Language Selection",
            "privacy" to "Privacy Policy",
            "rate" to "Rate Application",
            "share" to "Share Application",
            "remove_ads" to "Remove Ads (Premium)",
            "onboarding_1_title" to "Instant Food ID",
            "onboarding_1_desc" to "Point your camera or pick a picture of any vegetable, nut, spice or fruit to instantly recognize it with Advanced Vision AI.",
            "onboarding_2_title" to "Deep Health Science",
            "onboarding_2_desc" to "Get full organic profiles: detailed vitamins, minerals, shelf-life, and traditional Ayurvedic balancing characteristics.",
            "onboarding_3_title" to "Daily Portions Tracker",
            "onboarding_3_desc" to "Log your weights, see complete calorie limits and fulfill micronutrient goals easily offline.",
            "get_started" to "Get Started",
            "next" to "Next",
            "skip" to "Skip",
            "loading_scan" to "Analyzing food with Advanced AI...",
            "scan_now" to "Tap center to select/capture image",
            "or_quick_demo" to "Or select a quick demo crop below:",
            "unknown_food" to "Unidentified object. Position properly.",
            "scans_remaining" to "Sponsored Ad in next scan",
            "ad_banner_placeholder" to "NutriScan AI Sponsor Banner",
            "ad_interstitial_headline" to "Intermission Advertisement",
            "close_ad" to "Close Ad",
            "compare_button" to "Compare Items"
        ),
        "es" to mapOf(
            "app_title" to "NutriScan AI",
            "dashboard" to "Panel",
            "scanner" to "Escanear",
            "tracker" to "Nutrición",
            "favorites" to "Favoritos",
            "settings" to "Ajustes",
            "home" to "Inicio",
            "history" to "Historial Reciente",
            "no_scans" to "Sin escaneos aún. ¡Presiona escanear!",
            "categories" to "Explorar Categorías",
            "search_placeholder" to "Buscar alimentos o nombres científicos...",
            "voice_input" to "Presiona micrófono para buscar por voz",
            "compare" to "Comparar",
            "compare_title" to "Comparador",
            "select_to_compare" to "Compara alimentos lado a lado",
            "compare_select_prompt" to "Toca elementos del historial para comparar",
            "calories" to "Calorías",
            "protein" to "Proteínas",
            "carbohydrates" to "Carbohidratos",
            "fat" to "Grasas",
            "fiber" to "Fibra",
            "scientific_name" to "Nombre Científico",
            "category" to "Categoría",
            "origin" to "Origen",
            "season" to "Temporada Alta",
            "shelf_life" to "Vida Útil",
            "ayurvedic" to "Propiedades Ayurvédicas",
            "medicinal" to "Usos Medicinales",
            "benefits" to "Beneficios de Salud",
            "precautions" to "Precauciones y Seguridad",
            "allergies" to "Alergias",
            "recommended_daily" to "Consumo Recomendado",
            "add_to_tracker" to "Agregar a Dieta",
            "amount_grams" to "Cantidad consumida (gramos)",
            "save" to "Guardar",
            "cancel" to "Cancelar",
            "daily_summary" to "Objetivos Diarios",
            "goals" to "Metas Nutricionales",
            "edit_goals" to "Ajustar Objetivos",
            "theme" to "Tema de la App",
            "language" to "Idioma",
            "language_switch" to "Selección de Idioma",
            "privacy" to "Política de Privacidad",
            "rate" to "Calificar Aplicación",
            "share" to "Compartir Aplicación",
            "remove_ads" to "Quitar Anuncios (Premium)",
            "onboarding_1_title" to "ID de Comida al Instante",
            "onboarding_1_desc" to "Apunta tu cámara o sube fotos de cualquier cultivo para reconocerlo con la IA de Visión Inteligente.",
            "onboarding_2_title" to "Salud Profunda",
            "onboarding_2_desc" to "Obtén perfiles orgánicos: vitaminas, minerales, vida útil y propiedades Ayurvédicas.",
            "onboarding_3_title" to "Seguimiento de Dieta",
            "onboarding_3_desc" to "Registra pesos, calorías consumidas y cumple tus objetivos fácil y offline.",
            "get_started" to "Comenzar",
            "next" to "Siguiente",
            "skip" to "Saltar",
            "loading_scan" to "Analizando con IA Avanzada...",
            "scan_now" to "Toca para abrir cámara o galería",
            "or_quick_demo" to "O selecciona un demo rápido:",
            "unknown_food" to "Ininteligible. Colócalo bien.",
            "scans_remaining" to "Anuncio en el siguiente escaneo",
            "ad_banner_placeholder" to "Anuncio Patrocinado de NutriScan AI",
            "ad_interstitial_headline" to "Anuncio Comercial",
            "close_ad" to "Cerrar Anuncio",
            "compare_button" to "Comparar Alimentos"
        ),
        "hi" to mapOf(
            "app_title" to "NutriScan AI",
            "dashboard" to "डैशबोर्ड",
            "scanner" to "स्कैनर",
            "tracker" to "दैनिक डायरी",
            "favorites" to "पसंदीदा",
            "settings" to "सेटिंग्स",
            "home" to "होम",
            "history" to "हालिया स्कैन",
            "no_scans" to "अभी कोई स्कैन नहीं है। अभी स्कैन करें!",
            "categories" to "श्रेणियां ब्राउज़ करें",
            "search_placeholder" to "भोजन या वैज्ञानिक नाम खोजें...",
            "voice_input" to "आवाज से खोजने के लिए माइक दबाएं",
            "compare" to "तुलना करें",
            "compare_title" to "भोजन तुलना",
            "select_to_compare" to "एक साथ दो खाद्य पदार्थों की तुलना करें",
            "compare_select_prompt" to "तुलना के लिए भोजन का चयन करें",
            "calories" to "कैलोरी",
            "protein" to "प्रोटीन",
            "carbohydrates" to "कार्ब्स",
            "fat" to "वसा",
            "fiber" to "फाइबर",
            "scientific_name" to "वैज्ञानिक नाम",
            "category" to "श्रेणी",
            "origin" to "उत्पत्ति",
            "season" to "मुख्य सीजन",
            "shelf_life" to "सेल्फ लाइफ",
            "ayurvedic" to "आयुर्वेदिक गुण",
            "medicinal" to "चिकित्सीय उपयोग",
            "benefits" to "स्वास्थ्य लाभ",
            "precautions" to "सावधानियां",
            "allergies" to "एलर्जी",
            "recommended_daily" to "अनुशंसित दैनिक जीवन",
            "add_to_tracker" to "ट्रैकर में जोड़ें",
            "amount_grams" to "खपत मात्रा (ग्राम)",
            "save" to "सुरक्षित करें",
            "cancel" to "रद्द करें",
            "daily_summary" to "दैनिक लक्ष्य ट्रैकर",
            "goals" to "पोषण लक्ष्य",
            "edit_goals" to "दैनिक लक्ष्य बदलें",
            "theme" to "ऐप थीम",
            "language" to "ऐप भाषा",
            "language_switch" to "भाषा चयन",
            "privacy" to "गोपनीयता नीति",
            "rate" to "ऐप को रेट करें",
            "share" to "ऐप शेयर करें",
            "remove_ads" to "विज्ञापन हटाएं (प्रीमियम)",
            "onboarding_1_title" to "त्वरित खाद्य पहचान",
            "onboarding_1_desc" to "सब्जी, फल या मेवे की पहचान के लिए kamera घुमाएं और उन्नत विज़न एआई से त्वरित परिणाम पाएं।",
            "onboarding_2_title" to "गहन स्वास्थ्य विज्ञान",
            "onboarding_2_desc" to "विस्तृत विटामिन, खनिज, पारंपरिक आयुर्वेदिक संतुलन और स्वास्थ्य लाभ की पूरी जानकारी प्राप्त करें।",
            "onboarding_3_title" to "दैनिक पोषण ट्रैकिंग",
            "onboarding_3_desc" to "अपनी दैनिक कैलोरी, प्रोटीन, कार्ब्स और वसा लक्ष्यों को ऑफलाइन आसानी से व्यवस्थित करें।",
            "get_started" to "शुरू करें",
            "next" to "अगला",
            "skip" to "छोड़ें",
            "loading_scan" to "उन्नत विज़न एआई से खाद्य विश्लेषण चालू है...",
            "scan_now" to "कैमरा/गैलरी खोलने के लिए दबाएं",
            "or_quick_demo" to "या नीचे दिए गए आसान डेमो को चुनें:",
            "unknown_food" to "अपरिचित वस्तु। सही स्थान पर रखें।",
            "scans_remaining" to "प्रायोजित विज्ञापन अगले स्कैन पर",
            "ad_banner_placeholder" to "प्रायोजित विज्ञापन - न्यूट्रीस्कैन",
            "ad_interstitial_headline" to "प्रायोजित विज्ञापन रोक",
            "close_ad" to "विज्ञापन बंद करें",
            "compare_button" to "तुलना करें"
        ),
        "fr" to mapOf(
            "app_title" to "NutriScan AI",
            "dashboard" to "Tableau",
            "scanner" to "Scanner",
            "tracker" to "Journal",
            "favorites" to "Favoris",
            "settings" to "Réglages",
            "home" to "Accueil",
            "history" to "Scans Récents",
            "no_scans" to "Aucun scan. Appuyez sur scanner!",
            "categories" to "Parcourir les catégories",
            "search_placeholder" to "Rechercher des aliments...",
            "voice_input" to "Activer la recherche vocale",
            "compare" to "Comparer",
            "compare_title" to "Comparateur",
            "select_to_compare" to "Comparer côte à côte",
            "compare_select_prompt" to "Sélectionnez des aliments du journal pour comparer",
            "calories" to "Calories",
            "protein" to "Protéines",
            "carbohydrates" to "Glucides",
            "fat" to "Lipides",
            "fiber" to "Fibres",
            "scientific_name" to "Nom Scientifique",
            "category" to "Catégorie",
            "origin" to "Origine",
            "season" to "Saison",
            "shelf_life" to "Conservation",
            "ayurvedic" to "Propriétés Ayurvédiques",
            "medicinal" to "Usage Médicinal",
            "benefits" to "Bienfaits Santé",
            "precautions" to "Précautions",
            "allergies" to "Allergies",
            "recommended_daily" to "Apport Recommandé",
            "add_to_tracker" to "Ajouter au Journal",
            "amount_grams" to "Quantité consommée (grammes)",
            "save" to "Sauver",
            "cancel" to "Annuler",
            "daily_summary" to "Objectifs Quotidiens",
            "goals" to "Objectifs Nutritionnels",
            "edit_goals" to "Modifier Objectifs",
            "theme" to "Thème",
            "language" to "Langue",
            "language_switch" to "Sélection de la Langue",
            "privacy" to "Confidentialité",
            "rate" to "Évaluer l'application",
            "share" to "Partager l'application",
            "remove_ads" to "Supprimer les pubs (Premium)",
            "onboarding_1_title" to "Identification Instantanée",
            "onboarding_1_desc" to "Prenez ou séléctionnez une photo pour identifier instantanément via l'IA de Vision.",
            "onboarding_2_title" to "Profil Nutritionnel Complet",
            "onboarding_2_desc" to "Découvrez les vitamines, minéraux, usages médicinaux et équilibres Ayurvédiques.",
            "onboarding_3_title" to "Journal Quotidien",
            "onboarding_3_desc" to "Renseignez vos apports nutritionnels et suivez vos limites et objectifs en toute simplicité.",
            "get_started" to "Fermer",
            "next" to "Suivant",
            "skip" to "Passer",
            "loading_scan" to "Analyse en cours par l'IA...",
            "scan_now" to "Appuyez pour importer/capturer",
            "or_quick_demo" to "Ou séléctionnez un exemple:",
            "unknown_food" to "Inconnu. Positionnez correctement.",
            "scans_remaining" to "Publicité au prochain scan",
            "ad_banner_placeholder" to "Espace Publicitaire NutriScan AI",
            "ad_interstitial_headline" to "Promotion Logique",
            "close_ad" to "Fermer la publicité",
            "compare_button" to "Comparer"
        ),
        "de" to mapOf(
            "app_title" to "NutriScan AI",
            "dashboard" to "Übersicht",
            "scanner" to "Scanner",
            "tracker" to "Tagebuch",
            "favorites" to "Favoriten",
            "settings" to "Optionen",
            "home" to "Startseite",
            "history" to "Letzte Scans",
            "no_scans" to "Noch keine Scans. Tippe auf Scannen!",
            "categories" to "Kategorien",
            "search_placeholder" to "Suchen...",
            "voice_input" to "Tippe für Sprachsuche",
            "compare" to "Vergleich",
            "compare_title" to "Nahrungsvergleich",
            "select_to_compare" to "Nahrungsmittel nebeneinander vergleichen",
            "compare_select_prompt" to "Wähle Gegenstände zum Vergleichen",
            "calories" to "Kalorien",
            "protein" to "Eiweiß",
            "carbohydrates" to "Kohlenhydrate",
            "fat" to "Fett",
            "fiber" to "Ballaststoffe",
            "scientific_name" to "Wissenschaftlicher Name",
            "category" to "Kategorie",
            "origin" to "Herkunft",
            "season" to "Saison",
            "shelf_life" to "Haltbarkeit",
            "ayurvedic" to "Ayurveda-Eigenschaften",
            "medicinal" to "Heilwirkungen",
            "benefits" to "Gesundheitliche Vorteile",
            "precautions" to "Vorsichtsmaßnahmen",
            "allergies" to "Allergien",
            "recommended_daily" to "Empfohlene Dosis",
            "add_to_tracker" to "Ins Tagebuch eintragen",
            "amount_grams" to "Gewicht (Gramm)",
            "save" to "Speichern",
            "cancel" to "Abbrechen",
            "daily_summary" to "Tagesziele",
            "goals" to "Nährstoffziele",
            "edit_goals" to "Ziele anpassen",
            "theme" to "App-Design",
            "language" to "Sprache",
            "language_switch" to "Sprachauswahl",
            "privacy" to "Datenschutz",
            "rate" to "App bewerten",
            "share" to "App teilen",
            "remove_ads" to "Werbung entfernen (Premium)",
            "onboarding_1_title" to "Echtzeit Erkennung",
            "onboarding_1_desc" to "Richte deine Kamera auf Früchte, Gemüse oder Nüsse, um sie per Smart-Vision-KI zu identifizieren.",
            "onboarding_2_title" to "Heilwirkungsprofile",
            "onboarding_2_desc" to "Detaillierte Einsichten in Vitamine, Mineralstoffe, ayurvedische Balancen und medizinische Verwendungen.",
            "onboarding_3_title" to "Nährstoff-Tracker",
            "onboarding_3_desc" to "Trage deine Mahlzeiten ein und behalte deine Kalorien- und Proteingrenzen offline im Blick.",
            "get_started" to "Starten",
            "next" to "Weiter",
            "skip" to "Überspringen",
            "loading_scan" to "Analysiere mit Smart-KI...",
            "scan_now" to "Tippe für Kamera oder Galerie",
            "or_quick_demo" to "Oder wähle einen Demo-Artikel:",
            "unknown_food" to "Unbekannt. Bitte richtig platzieren.",
            "scans_remaining" to "Werbung beim nächsten Scan",
            "ad_banner_placeholder" to "Sponsor-Anzeige NutriScan AI",
            "ad_interstitial_headline" to "Werbepause",
            "close_ad" to "Werbung schließen",
            "compare_button" to "Vergleichen"
        ),
        "mr" to mapOf(
            "app_title" to "NutriScan AI",
            "dashboard" to "डॅशबोर्ड",
            "scanner" to "स्कॅनर",
            "tracker" to "दैनिक नोंद",
            "favorites" to "आवडते",
            "settings" to "सेटिंग्ज",
            "home" to "होम",
            "history" to "अलीकडील शोध",
            "no_scans" to "अद्याप कोणताही शोध नाही. स्कॅन करा!",
            "categories" to "कॅटेगरी शोधा",
            "search_placeholder" to "अन्न किंवा शास्त्रोक्त नाव शोधा...",
            "voice_input" to "आवाजाने शोधण्यासाठी माइक दाबा",
            "compare" to "तुलना करा",
            "compare_title" to "अन्न तुलना",
            "select_to_compare" to "दोन पदार्थांची तुलना करा",
            "compare_select_prompt" to "तुलनेसाठी पदार्थ निवडा",
            "calories" to "कॅलरी",
            "protein" to "प्रथिने (प्रोटीन)",
            "carbohydrates" to "कार्ब्स",
            "fat" to "चरबी (फॅट्स)",
            "fiber" to "फायबर",
            "scientific_name" to "शास्त्रीय नाव",
            "category" to "कॅटेगरी",
            "origin" to "उत्पत्ती",
            "season" to "मुख्य हंगาม",
            "shelf_life" to "टिकाऊपणा",
            "ayurvedic" to "आयुर्वेदिक गुण",
            "medicinal" to "औषधी उपयोग",
            "benefits" to "आरोग्य फायदे",
            "precautions" to "खबरदारी व सुरक्षा",
            "allergies" to "अॅलर्जी माहिती",
            "recommended_daily" to "शिफारस केलेले सेवन",
            "add_to_tracker" to "दैनिक नोंदणीत जोडा",
            "amount_grams" to "खाल्लेले प्रमाण (ग्रॅम)",
            "save" to "जतन करा",
            "cancel" to "रद्द करा",
            "daily_summary" to "दैनिक ध्येय ट्रॅकर",
            "goals" to "पोषण उद्दिष्टे",
            "edit_goals" to "ध्येय बदला",
            "theme" to "अ‍ॅप थीम",
            "language" to "अ‍ॅप भाषा",
            "language_switch" to "भाषा निवडा",
            "privacy" to "गोपनीयता धोरण",
            "rate" to "अ‍ॅपला रेटिंग द्या",
            "share" to "अ‍ॅप शेअर करा",
            "remove_ads" to "जाहिराती काढा (प्रीमियम)",
            "onboarding_1_title" to "झटपट अन्न ओळख",
            "onboarding_1_desc" to "प्रगत विजन एआय द्वारे ओळखण्यासाठी कॅमेरा फिरवा.",
            "onboarding_2_title" to "सखोल आरोग्य माहिती",
            "onboarding_2_desc" to "जीवनसत्त्वे, खनिजे आणि पारंपरिक आयुर्वेदिक गुणांची माहिती मिळवा.",
            "onboarding_3_title" to "दैनिक पोषण ट्रॅकर",
            "onboarding_3_desc" to "तुमची दैनिक ध्येये ऑफलाइन सहज ट्रॅक करा.",
            "get_started" to "सुरू करा",
            "next" to "पुढे",
            "skip" to "वगळा",
            "loading_scan" to "प्रगत एआय द्वारे विश्लेषण सुरू आहे...",
            "scan_now" to "कॅमेरा किंवा गॅलरी उघडण्यासाठी दाबा",
            "or_quick_demo" to "किंवा खालील डेमोमधून निवडा:",
            "unknown_food" to "अपरिचित वस्तू. योग्य ठिकाणी ठेवा.",
            "scans_remaining" to "पुढील स्कॅनवर जाहिरात",
            "ad_banner_placeholder" to "जाहिरात - न्यूट्रीस्कॅन",
            "ad_interstitial_headline" to "जाहिरात",
            "close_ad" to "जाहिरात बंद करा",
            "compare_button" to "तुलना करा"
        ),
        "pa" to mapOf(
            "app_title" to "NutriScan AI",
            "dashboard" to "ਡੈਸ਼ਬੋਰਡ",
            "scanner" to "ਸਕੈਨਰ",
            "tracker" to "ਰੋਜ਼ਾਨਾ ਡਾਇਰੀ",
            "favorites" to "ਮਨਪਸੰਦ",
            "settings" to "ਸੈਟਿੰਗਜ਼",
            "home" to "ਹੋਮ",
            "history" to "ਤਾਜ਼ਾ ਸਕੈਨ",
            "no_scans" to "ਅਜੇ ਕੋਈ ਸਕੈਨ ਨਹੀਂ ਹੈ। ਸਕੈਨ ਕਰੋ!",
            "categories" to "ਸ਼੍ਰੇਣੀਆਂ ਵੇਖੋ",
            "search_placeholder" to "ਭੋਜਨ ਜਾਂ ਵਿਗਿਆਨਕ ਨਾਮ ਲੱਭੋ...",
            "voice_input" to "ਆਵਾਜ਼ ਨਾਲ ਲੱਭਣ ਲਈ ਮਾਈਕ ਦਬਾਓ",
            "compare" to "ਤੁਲਨਾ ਕਰੋ",
            "compare_title" to "ਭੋਜਨ ਤੁਲਨਾ",
            "select_to_compare" to "ਦੋ ਚੀਜ਼ਾਂ ਦੀ ਤੁਲਨਾ ਕਰੋ",
            "compare_select_prompt" to "ਤੁਲਨਾ ਲਈ ਭੋਜਨ ਚੁਣੋ",
            "calories" to "ਕੈਲੋਰੀ",
            "protein" to "ਪ੍ਰੋਟੀਨ",
            "carbohydrates" to "ਕਾਰਬਸ",
            "fat" to "ਚਰਬੀ (ਫੈਟ)",
            "fiber" to "ਫਾਈਬਰ",
            "scientific_name" to "ਵਿਗਿਆਨਕ ਨਾਮ",
            "category" to "ਸ਼੍ਰੇਣੀ",
            "origin" to "ਉਤਪੱਤੀ",
            "season" to "ਖਾਸ ਸੀਜ਼ਨ",
            "shelf_life" to "ਸ਼ੈਲਫ ਲਾਈਫ",
            "ayurvedic" to "ਆਯੁਰਵੈਦਿਕ ਵਿਸ਼ੇเศษਤਾ",
            "medicinal" to "ਦਵਾਈ ਦੀ ਵਰਤੋਂ",
            "benefits" to "ਸਿਹਤ ਲਾਭ",
            "precautions" to "ਸਾਵਧਾਨੀਆਂ",
            "allergies" to "ਐਲਰਜੀ ਜਾਣਕਾਰੀ",
            "recommended_daily" to "ਸਿਫਾਰਸ਼ ਕੀਤੀ ਖੁਰਾਕ",
            "add_to_tracker" to "ਡਾਇਰੀ ਵਿੱਚ ਜੋੜੋ",
            "amount_grams" to "ਮਾਤਰਾ (ਗ੍ਰਾਮ)",
            "save" to "ਸੁਰੱਖਿਅत ਕਰੋ",
            "cancel" to "ਰੱਦ ਕਰੋ",
            "daily_summary" to "ਰੋਜ਼ਾਨਾ ਟੀਚਾ ਟਰੈਕਰ",
            "goals" to "ਪੋਸ਼ਣ ਟੀਚਾ",
            "edit_goals" to "ਰੋਜ਼ਾਨਾ ਟੀਚਾ ਬਦਲੋ",
            "theme" to "ਐਪ ਥੀਮ",
            "language" to "ਐਪ ਭਾਸ਼ਾ",
            "language_switch" to "ਭਾਸ਼ਾ ਚੁਣੋ",
            "privacy" to "ਪ੍ਰਾਈਵੇਸੀ ਪਾਲਿਸੀ",
            "rate" to "ਐਪ ਨੂੰ ਰੇਟ ਕਰੋ",
            "share" to "ਐਪ ਸ਼ੇਅਰ ਕਰੋ",
            "remove_ads" to "ਵਿਗਿਆਪਨ ਹਟਾਓ (ਪ੍ਰੀਮੀਅਮ)",
            "onboarding_1_title" to "ਤੁਰੰਤ ਭੋਜਨ ਪਛਾਣ",
            "onboarding_1_desc" to "ਉੱਨਤ ਵਿਜ਼ਨ AI ਨਾਲ ਤੁਰੰਤ ਪਛਾਣਨ ਲਈ ਕੈਮਰਾ ਘੁਮਾਓ।",
            "onboarding_2_title" to "ਡੂੰਘੀ ਸਿਹਤ ਜਾਣਕਾਰੀ",
            "onboarding_2_desc" to "ਵਿਟਾਮਿਨ, ਖਣਿਜ ਅਤੇ ਆਯੁਰਵੈਦਿਕ ਸੰਤੁਲਨ ਦੀ ਪੂਰੀ ਜਾਣਕਾਰੀ ਲਓ।",
            "onboarding_3_title" to "ਰੋਜ਼ਾਨਾ ਪੋਸ਼ਣ ਟਰੈਕਰ",
            "onboarding_3_desc" to "ਆਪਣੇ ਰੋਜ਼ਾਨਾ ਟੀਚਿਆਂ ਨੂੰ ਆਫਲਾਈਨ ਆਸਾਨੀ ਨਾਲ ਵਿਵਸਥਿਤ ਕਰੋ।",
            "get_started" to "ਸ਼ੁਰੂ ਕਰੋ",
            "next" to "ਅੱਗੇ",
            "skip" to "ਛੱਡੋ",
            "loading_scan" to "ਉੱਨਤ AI ਨਾਲ ਵਿਸ਼ਲੇਸ਼ਣ ਚੱਲ ਰਿਹਾ ਹੈ...",
            "scan_now" to "ਕੈਮਰਾ ਜਾਂ ਗੈਲਰੀ ਖੋਲ੍ਹਣ ਲਈ ਦਬਾਓ",
            "or_quick_demo" to "ਜਾਂ ਹੇਠਾਂ ਦਿੱਤੇ ਡੈਮੋ ਵਿੱਚੋਂ ਚੁਣੋ:",
            "unknown_food" to "ਅਣਜਾਣ ਚੀਜ਼। ਸਹੀ ਜਗ੍ਹਾ 'ਤੇ ਰੱਖੋ।",
            "scans_remaining" to "ਅਗਲੇ ਸਕੈਨ 'ਤੇ ਵਿਗਿਆਪਨ",
            "ad_banner_placeholder" to "ਵਿਗਿਆਪਨ - ਨਿਊਟ੍ਰੀਸਕੈਨ",
            "close_ad" to "ਵਿਗਿਆਪਨ ਬੰਦ ਕਰੋ",
            "compare_button" to "ਤੁਲਨਾ ਕਰੋ"
        ),
        "te" to mapOf(
            "app_title" to "NutriScan AI",
            "dashboard" to "డ్యాష్‌బోర్డ్",
            "scanner" to "స్కానర్",
            "tracker" to "ఆహార దినచర్య",
            "favorites" to "ఇష్టమైనవి",
            "settings" to "సెట్టింగ్స్",
            "home" to "హోమ్",
            "history" to "ఇటీవలి స్కాన్లు",
            "no_scans" to "ఇంకా స్కాన్లు లేవు. ఇప్పుడే స్కాన్ చేయండి!",
            "categories" to "విభాగాలు",
            "search_placeholder" to "ఆహారం లేదా శాస్త్రీయ నామం శోధించండి...",
            "voice_input" to "వాయిస్ శోధన కోసం మైక్ నొక్కండి",
            "compare" to "పోల్చండి",
            "compare_title" to "ఆహార పోలిక",
            "select_to_compare" to "ఆహారాలను పక్కపక్కనే పోల్చండి",
            "compare_select_prompt" to "పోలిక కొరకు ఆహారాన్ని ఎంచుకోండి",
            "calories" to "కలరీలు",
            "protein" to "ప్రోటీన్",
            "carbohydrates" to "కార్బ్స్",
            "fat" to "క్రొవ్వులు",
            "fiber" to "ఫైబర్",
            "scientific_name" to "శాస్త్రీయ నామం",
            "category" to "వర్గం",
            "origin" to "మూలము",
            "season" to "సీజన్",
            "shelf_life" to "నిల్వ కాలం",
            "ayurvedic" to "ఆయుర్వేద గుణాలు",
            "medicinal" to "ఔషధ ఉపయోగాలు",
            "benefits" to "ఆరోగ్య ప్రయోజనాలు",
            "precautions" to "జాగ్రత్తలు",
            "allergies" to "అలెర్జీ సమాచారం",
            "recommended_daily" to "రోజువారీ మోతాదు",
            "add_to_tracker" to "డైరీకి చేర్చండి",
            "amount_grams" to "పరిమాణం (గ్రాములు)",
            "save" to "సేవ్ చేయండి",
            "cancel" to "రద్దు చేయండి",
            "daily_summary" to "రోజువారీ లక్ష్యాలు",
            "goals" to "పోషకాహార లక్ష్యాలు",
            "edit_goals" to "లక్ష్యాలను సవరించండి",
            "theme" to "యాప్ థీమ్",
            "language" to "యాప్ భాష",
            "language_switch" to "భాషను ఎంచుకోండి",
            "privacy" to "గోప్యతా విధానం",
            "rate" to "రేట్ చేయండి",
            "share" to "షేర్ చేయండి",
            "remove_ads" to "ప్రకటనలను తొలగించండి",
            "onboarding_1_title" to "త్వరిత ఆహార గుర్తింపు",
            "onboarding_1_desc" to "అధునాతన విజన్ AIతో తక్షణమే గుర్తించడానికి కెమెరాను చూపండి.",
            "onboarding_2_title" to "ఆరోగ్య విశ్లేషణ",
            "onboarding_2_desc" to "విటమిన్లు, ఖనిజాలు మరియు ఆయుర్వేద గుణాల సమాచారం పొందండి.",
            "onboarding_3_title" to "రోజువారీ పోషకాహార ట్రాకర్",
            "onboarding_3_desc" to "మీ రోజువారీ లక్ష్యాలను ఆఫ్‌లైన్‌లో సులభంగా నిర్వహించండి.",
            "get_started" to "ప్రారంభించండి",
            "next" to "తరువాత",
            "skip" to "వదిలేయి",
            "loading_scan" to "అధునాతన AI గుర్తిస్తోంది...",
            "scan_now" to "కెమెరా లేదా గ్యాలరీ తెరవడానికి నొక్కండి",
            "or_quick_demo" to "లేదా కింద డెమో ఎంచుకోండి:",
            "unknown_food" to "అపరిచిత వస్తువు. సరిగ్గా ఉంచండి.",
            "scans_remaining" to "తదుపరి స్కాన్‌లో ప్రకటన",
            "ad_banner_placeholder" to "ప్రకటన",
            "close_ad" to "ముగించు",
            "compare_button" to "పోల్చు"
        )
    )

    fun getString(key: String, lang: String): String {
        return dictionary[lang]?.get(key) ?: dictionary["en"]?.get(key) ?: key
    }
}
